preload = /home/sk7x/.assets/wallpapers/assassins-creed-12000x6871-16786.jpeg

wallpaper {
    monitor = eDP-1
    path = /home/sk7x/.assets/wallpapers/assassins-creed-12000x6871-16786.jpeg
    fit_mode = cover
}

splash = false
